# Generated by Django 4.1.3 on 2022-12-11 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0002_departments_created_alter_departments_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='Doct_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='opdate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='p_problem',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='time_slot',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='tokenNum',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
